# Generated by Django 4.2.21 on 2025-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.CharField(help_text='e.g. 6 Mbps', max_length=20)),
                ('price', models.CharField(help_text='e.g. KSh 1,500/month', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('features', models.TextField(help_text='One feature per line')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Internet Package',
                'verbose_name_plural': 'Internet Packages',
                'ordering': ['order', 'speed'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
