# Generated by Django 4.2.21 on 2025-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internetpackage_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary for listings', max_length=300)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Hyperwave Networks', max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time', models.IntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='internetpackage',
            name='coverage_areas',
            field=models.TextField(blank=True, help_text='Areas where this package is available'),
        ),
        migrations.AddField(
            model_name='internetpackage',
            name='target_audience',
            field=models.CharField(blank=True, help_text='e.g. Small Business, Home Users', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='county',
            field=models.CharField(blank=True, help_text='County/Region', max_length=50),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='population',
            field=models.IntegerField(blank=True, help_text='Approximate population for local SEO', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specialties',
            field=models.CharField(blank=True, help_text='Comma-separated skills/specialties', max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_experience',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, help_text='City/Location for local SEO', max_length=100),
        ),
    ]
