# Generated by Django 4.2.21 on 2025-06-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_internetpackage_coverage_areas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='internetpackage',
            name='coverage_areas',
        ),
        migrations.RemoveField(
            model_name='internetpackage',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='county',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='population',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='years_experience',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='location',
        ),
    ]
